import os
import sys
import importlib
import pygame

os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "HIDE"
screen = None

class Engine:
    screen = None
    clock = None
    running = False
    loaded_scripts = set()  # scripts déjà chargés

    @staticmethod
    def Init(width=800, height=800):
        pygame.init()
        Engine.screen = pygame.display.set_mode((width, height))
        Engine.clock = pygame.time.Clock()
        Engine.running = True
        Engine.screen.fill((0, 0, 0))
        pygame.display.flip()

    @staticmethod
    def Run():
        from UnipyEngine.Core import GameObject

        while Engine.running:
            Engine.screen.fill((0, 0, 0))
            dt = Engine.clock.tick(60) / 1000.0

            for gameObject in GameObject.instances:
                for component in gameObject.components:
                    if hasattr(component, "Update") and callable(component.Update):
                        component.Update(dt)

            pygame.display.flip()

            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    Engine.running = False

        pygame.quit()

    @staticmethod
    def LoadScripts(folder="Assets"):
        if not os.path.exists(folder):
            print(f"UnipyEngine: Scripts folder '{folder}' not found")
            return

        # Vérifier si __init__.py existe et récupérer les scripts déjà listés
        init_file = os.path.join(folder, "__init__.py")
        if os.path.exists(init_file):
            with open(init_file, "r", encoding="utf-8") as f:
                lines = f.readlines()
                Engine.loaded_scripts = set(line.strip().split()[1].lstrip(".") 
                                            for line in lines if line.startswith("from ."))

        # lister tous les fichiers .py dans le dossier
        current_files = set(os.path.splitext(f)[0] for f in os.listdir(folder) if f.endswith(".py") and f != "__init__.py")

        # détecter les nouveaux scripts
        new_files = current_files - Engine.loaded_scripts
        if new_files:
            # régénérer __init__.py automatiquement
            with open(init_file, "w", encoding="utf-8") as f:
                f.write("# Auto-generated by UnipyEngine.Engine\n")
                for module_name in current_files:
                    f.write(f"from .{module_name} import *\n")

            Engine.loaded_scripts.update(current_files)
            print("UnipyEngine: New scripts detected. Reloading complete.")
            sys.exit(0)  # stop pour le premier run avec scripts nouveaux

        # charger les scripts existants
        for module_name in current_files:
            path = os.path.join(folder, f"{module_name}.py")
            spec = importlib.util.spec_from_file_location(module_name, path)
            module = importlib.util.module_from_spec(spec)
            sys.modules[module_name] = module
            try:
                spec.loader.exec_module(module)
                print(f"UnipyEngine : [{module_name}] loaded successfully")
                # injecter les classes dans globals()
                for name, obj in module.__dict__.items():
                    if isinstance(obj, type):
                        globals()[name] = obj
            except Exception as e:
                print(f"UnipyEngine : Error loading {module_name} -> {e}")
