import os
import sys
import importlib
import pygame
import json

os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "HIDE"
screen = None

class Engine:
    screen = None
    clock = None
    running = False
    loaded_scripts = set()  # scripts déjà connus

    @staticmethod
    def Init(width=800, height=800):
        pygame.init()
        Engine.screen = pygame.display.set_mode((width, height))
        Engine.clock = pygame.time.Clock()
        Engine.running = True
        Engine.screen.fill((0, 0, 0))
        pygame.display.flip()

    @staticmethod
    def Run():
        from UnipyEngine.Core import GameObject

        while Engine.running:
            Engine.screen.fill((0, 0, 0))
            dt = Engine.clock.tick(60) / 1000.0

            for gameObject in GameObject.instances:
                for component in gameObject.components:
                    if hasattr(component, "Update") and callable(component.Update):
                        component.Update(dt)

            pygame.display.flip()

            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    Engine.running = False

        pygame.quit()

    @staticmethod
    def LoadScripts(folder="Assets"):
        if not os.path.exists(folder):
            print(f"UnipyEngine: Scripts folder '{folder}' not found")
            return

        init_file = os.path.join(folder, "__init__.py")
        cache_file = os.path.join(folder, ".engine_cache.json")

        # lire la liste des scripts précédemment connus
        if os.path.exists(cache_file):
            with open(cache_file, "r", encoding="utf-8") as f:
                try:
                    Engine.loaded_scripts = set(json.load(f))
                except Exception:
                    Engine.loaded_scripts = set()

        # scripts réellement présents
        current_files = set(
            os.path.splitext(f)[0]
            for f in os.listdir(folder)
            if f.endswith(".py") and f != "__init__.py"
        )

        # régénérer __init__.py (toujours synchro)
        with open(init_file, "w", encoding="utf-8") as f:
            f.write("# Auto-generated by UnipyEngine.Engine\n")
            for module_name in current_files:
                f.write(f"from .{module_name} import *\n")

        # comparer avec l’ancien état
        new_files = current_files - Engine.loaded_scripts
        removed_files = Engine.loaded_scripts - current_files

        if new_files or removed_files:
            # sauvegarder le nouvel état dans le cache
            with open(cache_file, "w", encoding="utf-8") as f:
                json.dump(list(current_files), f)

            print("UnipyEngine: Script set changed. Reloading complete.")
            sys.exit(0)
