import os
import sys
import importlib
import pygame

os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "HIDE"

screen = None
loaded_scripts = set()  # pour suivre les fichiers déjà chargés

class Engine:
    screen = None
    clock = None
    running = False

    @staticmethod
    def Init(width=800, height=800):
        pygame.init()
        Engine.screen = pygame.display.set_mode((width, height))
        Engine.clock = pygame.time.Clock()
        Engine.running = True
        Engine.screen.fill((0, 0, 0))
        pygame.display.flip()

    @staticmethod
    def Run():
        from UnipyEngine.Core import GameObject

        while Engine.running:
            Engine.screen.fill((0, 0, 0))
            dt = Engine.clock.tick(60) / 1000.0

            for gameObject in GameObject.instances:
                for component in gameObject.components:
                    if hasattr(component, "Update") and callable(component.Update):
                        component.Update(dt)

            pygame.display.flip()

            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    Engine.running = False

        pygame.quit()

    @staticmethod
    def LoadScripts(folder="Assets"):
        global loaded_scripts

        if not os.path.exists(folder):
            print(f"UnipyEngine: Scripts folder '{folder}' not found")
            return

        # lister les fichiers .py
        current_files = set(f for f in os.listdir(folder) if f.endswith(".py"))
        new_files = current_files - loaded_scripts

        if new_files:
            # régénérer __init__.py automatiquement
            init_file = os.path.join(folder, "__init__.py")
            with open(init_file, "w", encoding="utf-8") as f:
                f.write("# Auto-generated by UnipyEngine.Engine\n")
                for file in current_files:
                    if file != "__init__.py":
                        module_name = os.path.splitext(file)[0]
                        f.write(f"from .{module_name} import *\n")

            loaded_scripts.update(current_files)
            print("UnipyEngine: New scripts detected. Reloading complete.")
            # arrêt automatique du run
            sys.exit(0)

        # charger les scripts existants
        for file in current_files:
            if file != "__init__.py":
                path = os.path.join(folder, file)
                module_name = os.path.splitext(file)[0]

                spec = importlib.util.spec_from_file_location(module_name, path)
                module = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = module

                try:
                    spec.loader.exec_module(module)
                    print(f"UnipyEngine : [{module_name}] loaded successfully")

                    for name, obj in module.__dict__.items():
                        if isinstance(obj, type):
                            globals()[name] = obj

                except Exception as e:
                    print(f"UnipyEngine : Error loading {module_name} -> {e}")
